### ISSUE TITLE
Train and Test

### ISSUE THREAD

**Issue by AminTolou** [icandle/MAN#10]
Can we train and Test another SR Model such as SAN and RCAN in your code?
If Possible please Write Details.
Thanks for Your Response.

**Comment by icandle** [comment]
Our training and testing codes are based on [BasicSR](https://github.com/XPixelGroup/BasicSR). It includes the training config and details of RCAN and SAN. Moreover, for RCAN training,[RCAN-it](https://github.com/zudi-lin/rcan-it) is another impressive work to follow.
