### ISSUE TITLE
Post-training models

### ISSUE THREAD

**Issue by GoPikachue** [icandle/MAN#11]
First of all, thank you for your outstanding work! I would like to ask if the post-training model file for MAN is available.
    Looking forward to your reply!!!

**Comment by icandle** [comment]
All involved models are available at  [Baidu Pan](https://pan.baidu.com/s/15CTY-mgdTuOc1I8mzIA4Ug?pwd=mans).

**Comment by GoPikachue** [comment]
Amazing!!!

**Comment by GoPikachue** [comment]
Incredibly fast response time.
