### ISSUE TITLE
自集成问题

### ISSUE THREAD

**Issue by EchoXu98** [icandle/MAN#13]
您好，我想请问下，模型使用自集成策略（如MAN和使用了自集成后的MAN+）后可以进一步提升效果，在代码中如何设置才能使用这种自集成方式来训练或者测试模型呢？

**Comment by EchoXu98** [comment]
谢谢您的回复。我还有一个问题。就是我在训练这个代码时，先保持所有不变的情况下训练了大约200000次迭代，并保存了模型。假设我现在需要将学习率下降一半，那我应该去更改options/train_MAN.yml中scheduler下的milestones这个列表，但是我更改了将列表中的第一个数改为2000000，并重新从断点处开始训练，但是学习率并没有变化。我不知道这是为什么？学习率不应该减少一半吗？再次感谢您能抽空回答我的疑问！

**Comment by icandle** [comment]
emmm, 我的理解是这种情况重新训练的话就只恢复pretrain_network_g，不resume_state，然后重新定义milestones和total_iter，好像resume_state里包含了之前的学习率和断点信息吧，我不太确定。

**Comment by EchoXu98** [comment]
是的，我刚才debug了一下basic的源码，发现确实在读取的模型states里包含了之前设置的milestones，再改是无效的。谢谢您提供给我的方案，我觉得这是一个可行的方案。我和我的师兄在使用大核构建自己的模型时都出现了损失nan的情况然后psnr等指标变得很小，导致之后的训练都是无效的，请问您在之前有遇见过吗？

**Comment by icandle** [comment]
可能是大核模型里面涉及到的乘操作太多了，我在不使用norm或使用batch norm的时候遇到过，如下图：
![image](https://user-images.githubusercontent.com/39293311/227201048-fe6c42d2-7fd7-4eba-b53b-58a578366585.png)
如果layer norm都解决不了的话，可能要使用到重参数或者增加其他约束条件，或者其他学习策略，比如更小的学习率。

**Comment by icandle** [comment]
先裁剪乘比如说HR剪裁为640x640, 然后改变gt_size这个参数，小于640的皆可

**Comment by EchoXu98** [comment]
好的，那您是使用BasicSR框架中scripts/data_preparation/extract_subimages.py代码进行裁剪的吗？如果是的，您的crop_size,step等参数设置的是多少？如下图所示，最后在统计您裁剪图片的名称信息进入data/meta_info/meta_info_DF2Ksub_GT.txt时，共有多少张图片？
![image](https://user-images.githubusercontent.com/116281804/227425328-4785eef2-4b86-474f-a981-897a3b39dd81.png)

**Comment by icandle** [comment]
一般step是crop_size的一般即可，如果要更小，1/3也行，取决于你们自己的设定.

**Comment by EchoXu98** [comment]
其实我不明白的一点是，比如我在裁剪一对LR和HR数据，当设置不同大小的crop_size时将对LR-HR对图像生成不同数目的patch对数据，而生成数据的多少不会影响训练的效果吗？我假设这样一个训练场景，网络的训练时的gt_size=128，有一对LR-HR图像（并假设其尺寸分别是512x512和1024x1024），我裁剪的crop_size=128,step=128，那么我将从这对LR-HR图像中裁剪16对LR_HR对训练的子图像，如果我将裁剪的crop_size=256,step=256，那么此时我只能裁剪出4对LR_HR训练子图像。那么不是前一个裁剪设置下有更多的数据进行训练了？

**Comment by icandle** [comment]
不是，你剪裁的时候有一个over lap的情况，你的step不能和crop_size，不然你有些图片信息没利用到。同时就算是你第一种剪裁生成的子图更多，但是并没有新的信息在里面啊，都是一张图。你裁剪的时候只要保证你的裁剪不会影响到某些区域你得不到就行，就比如你step和crop_size都是128，那你两张图片之间的部分就没办法得到。
