### ISSUE TITLE
多卡训练问题

### ISSUE THREAD

**Issue by EchoXu98** [icandle/MAN#14]
您好，我又来请教问题了，关于多卡训练。是这样我之前用的一张3090的卡训练MAN-light，我发现它所占显存并不大，所以现在换成了2张3080卡做多卡训练，想加快训练速度。在使用多卡训练时，我只改变了trian_MAN.yml中的num_gpu数。相对于单卡训练，我使用多卡训练时，是不是还要改变训练迭代的总次数？比如之前单卡时训练的总迭代次数为1600K，现在用两张卡，总迭代次数是不是应该减半？我训练时终端的输出如下图
![image](https://user-images.githubusercontent.com/116281804/227718916-6b0caa8a-5d49-4465-8fa2-ffe674e9b846.png)

**Comment by icandle** [comment]
嗯，对的，可以减半。

**Comment by EchoXu98** [comment]
同时，在我的训练文件中生成了两个训练文件，每个训练文件对应一张卡，就好像并不是在做多卡训练，而是两张卡各自在训练各自的。如下图所示。在训练的过程中，这两个文件是同时在更新的。请问您在多卡训练时也是这样的吗？
![image](https://user-images.githubusercontent.com/116281804/227719062-48d92e43-859f-4fd4-933d-b2d172c0b1f2.png)

**Comment by icandle** [comment]
不吧，第二个好像是覆盖上一次的文件吧。我没遇到过同时更新的。

**Comment by EchoXu98** [comment]
> 嗯，对的，可以减半。
那同时，我的测试指标频率（val_freq）和保存模型频率（save_checkpoint_freq）是不是也应该减半？比如我之前用的单卡，然后裁剪出了1万张子图像（举例），然后我的batch_size设为8，所以我为了在每个epoch结束后保存并测试模型指标，将测试频率和保存模型频率都设置为（1万/8）,现在我用两张卡训练，是不是应该将测试模型频率和保存模型的频率都减小一半？

**Comment by EchoXu98** [comment]
> 嗯，对的，可以减半。
那同时，我的测试指标频率（val_freq）和保存模型频率（save_checkpoint_freq）是不是也应该减半？比如我之前用的单卡，然后裁剪出了1万张子图像（举例），然后我的batch_size设为8，所以我为了在每个epoch结束后保存并测试模型指标，将测试频率和保存模型频率都设置为（1万/8）,现在我用两张卡训练，是不是应该将测试模型频率和保存模型的频率都减小一半？

**Comment by icandle** [comment]
这个频率其实不怎么影响，因为基本上最好的结果都是在最后几次。当然，理论上应该都减小一半。

**Comment by EchoXu98** [comment]
> 不吧，第二个好像是覆盖上一次的文件吧。我没遇到过同时更新的。

我这边好像是出现了同时更新，但刚才没有跑完一个epoch，所以没有保存模型和状态，现在跑完一个epoch后发现只在第一个文件中保存模型和状态。

**Comment by EchoXu98** [comment]
> 这个频率其实不怎么影响，因为基本上最好的结果都是在最后几次。当然，理论上应该都减小一半。

哈哈，感谢大佬的光速回复！

**Comment by icandle** [comment]
没事没事，一起交流，互相学习。
