### ISSUE TITLE
在调优阶段的学习率更新策略问题

### ISSUE THREAD

**Issue by EchoXu98** [icandle/MAN#15]
大佬，我看到在论文中初始学习率更新策略采用的是cosine annealing learning策略，初始学习率为5e-4，但是在调优阶段只写了初始学习率为1e-4，没有写更新策略。请问还是使用的cosine annealing learning策略吗？但是我看train_MAN.yml文件中，有一个类型为MutiStepLR的策略，图一是论文中的截图，图二是train_MAN.yml相应部分的截图。
![image](https://user-images.githubusercontent.com/116281804/227815610-daa5a5e3-2324-4229-a070-353121230095.png)

![image](https://user-images.githubusercontent.com/116281804/227815660-56bdc811-5507-4b11-8107-0362828a02c8.png)

**Comment by icandle** [comment]
是的。

**Comment by EchoXu98** [comment]
> 是的。
好的，那就是仍然使用cosine annealing learning来更新学习率，其中初始学习率从1e-4开始吗？

**Comment by icandle** [comment]
对的对的，其实MutiStepLR也行的。

**Comment by EchoXu98** [comment]
谢谢大佬的快速回复，最近在做复现实验，所以问题比较多，打搅您的工作了。同时我看到论文中提到初次训练是迭代160K，但是实际设置时是1600K，那么调优阶段论文中写的是80K，实际是不是应该是800K？

**Comment by icandle** [comment]
对的，初版没改

**Comment by EchoXu98** [comment]
我在调优时，是直接从初次训练的最后一个epoch保存的模型开始训练吗？但是模型的state是不需要继承的？

**Comment by icandle** [comment]
对，finetuning的时候，只需要模型

**Comment by EchoXu98** [comment]
从初次训练的最后一个epoch保存的模型开始调优训练？

**Comment by icandle** [comment]
对的，和HAT一样

**Comment by EchoXu98** [comment]
好，谢谢佬！
