### ISSUE TITLE
关于FLOPs的计算

### ISSUE THREAD

**Issue by GoPikachue** [icandle/MAN#16]
![D2@5$LQBL 4L1DSY2}I}G 3](https://user-images.githubusercontent.com/57658728/228273061-bec4dcf2-fb75-489e-b509-6de396fa9633.png)
你好~
我想问一下论文里面的FLOPs是怎么计算的呀？
另外Swinir的X2X3的预训练标识是怎么理解？

**Comment by icandle** [comment]
MAdds和FLOPs，对于CNN，你可以参照[pytorch-OpCounter](https://github.com/Lyken17/pytorch-OpCounter) 或者torchsummaryX和torchstat以及[KAIR](https://github.com/cszn/KAIR)，至于SwinIR，他们提供了[flops函数](https://github.com/JingyunLiang/SwinIR/blob/main/models/network_swinir.py)和结果。预训练标识是SwinIR使用x2的结果继续训练x3和x4的模型。

**Comment by GoPikachue** [comment]
就是我想问一下论文里面那个是按照输入尺寸是多少来计算呀？

**Comment by icandle** [comment]
输出是1080*720的情况，4倍就是320*180。

**Comment by GoPikachue** [comment]
好~谢谢你的及时答复！
