### ISSUE TITLE
关于复现MAN-light低于论文结果的问题

### ISSUE THREAD

**Issue by EchoXu98** [icandle/MAN#17]
大佬，最近我按照论文中的设置跑了一遍MAN-light，但是并没有达到论文中的指标。如下为我训练完后各测试集的指标：
![image](https://user-images.githubusercontent.com/116281804/230600875-1d4edcfd-5381-4f33-b822-1ce0cefd20e1.png)
后来，我使用了你给出的测试集进行测试，效果稍微好了一点，但是还是没有达到论文中的效果。我想是否因为我的训练集出了问题？可能是因为我的训练集不是从官网中直接下载的缘故。同时，我还是想询问下之前询问过的问题，我们的训练集要先裁剪成小的patch再送入网络进行训练，其中您所设置的裁剪LR图像的‘crop_size’和'step'以及裁剪HR图像的'crop_size'和‘step’分别是多少？3450张DF2K图像一共裁剪出多少张patch图像？

**Comment by icandle** [comment]
crop_size和step分别是640和320，具体多少张我现在换成LSDIR了所以不太清楚。其实差距也没有这么大，说实话可能是种子的问题。但如果想要Set5和Manga109更高一点的话可以尝试一下更大的gt_size。

|<sub> model <sub>| <sub> Set5 </sub> | <sub> Set14 </sub> | <sub> BSD100 </sub> | <sub> Urban100 </sub> |  <sub> Manga109 </sub> | 
|  :----:  |  :----:  | :----:  |  :----:  | :----:  |  :----:  | 
|  Ours  |  **38.18**/0.9612  |  33.93/0.9213  |  **32.36**/0.9022  | 32.92/**0.9364**  |  **39.44**/**0.9786**  |
|            |  38.13/**0.9615**  |  **33.95**/**0.9215**  |  **32.36**/**0.9028**  | **32.93**/0.9357  |  39.35/0.9785  |

**Comment by EchoXu98** [comment]
大佬，再问一个问题。关于分布式训练，我使用了你提供在README中的命令“python -m torch.distributed.launch --nproc_per_node=2 --master_port=4321 train.py -opt options/trian_MAN.yml”（做了适当修改）进行训练，之前训练是完全没有问题的，通过上面的命令使用的是分布式中的DDP进行训练。但是训练结束后，我使用同样的命令再训练后，使用的DP进行训练非常消耗时间，无论我怎样修改都不能使用DDP进行训练了。
之前的训练：
![EGH`U2Z`~B5O0BM50A 0Y`Q](https://user-images.githubusercontent.com/116281804/230714599-40ea118c-5420-4fcc-ab09-d618b881d4ca.png)
![U2DLJH}4O6HO$K`2Y_RQ `Y](https://user-images.githubusercontent.com/116281804/230714603-184f7fab-e32f-4933-9b3d-30c94e15de7a.png)
新的训练：
![1SNT$QLNZ`5`93J3X2DSFA6](https://user-images.githubusercontent.com/116281804/230714612-78f47820-171b-47cc-b7b7-7ff8a7219215.png)
![G P61@R9`}PAL156L1TYT1A](https://user-images.githubusercontent.com/116281804/230714614-9e43d62c-165b-4531-940a-d07d434348c3.png)
上面是训练过程中的log记录。实在不知道怎么解决了才打搅您！

**Comment by icandle** [comment]
第二次我看只有一张gpu啊从log上看，你可以先试试是不是两张都可用

**Comment by EchoXu98** [comment]
对，但是无论我怎样改，world size都是1，但是跑的时候却是两张卡都在跑。其实我一共发了四张图，只不过这里的背景是白色的看不出来而已。您看第二张图和第四张图，它们各自所采用的分布式训练方式不同，我前后采用相同的命令运行，环境也保持的一样，不知道问题出在什么地方？

**Comment by icandle** [comment]
如果加了CUDA_VISIBLE_DEVICES=0,1，那我也不太清楚是怎么回事。

**Comment by EchoXu98** [comment]
解决了大佬，如果您以后遇见同样的问题可以这样修改
![image](https://user-images.githubusercontent.com/116281804/230722328-374826ca-8c2e-447c-815f-b7e98bc3b23b.png)

**Comment by icandle** [comment]
OKOK 受教了
