### ISSUE TITLE
关于亚像素卷积上采样的问题

### ISSUE THREAD

**Issue by GoPikachue** [icandle/MAN#18]
作者你好！
我想请教一下MAN代码里面的上采样，上面是先把维度从180降到3*scale^2，这样子会不会对亚像素卷积的上采样效果产生影响呀？
![image](https://user-images.githubusercontent.com/57658728/231183903-41726072-14d2-4baa-a9d9-77be38540741.png)
期待你的答复！！！

**Comment by icandle** [comment]
没关系，你要的觉得这样不保险，可以在tail前先从180降到3*scale^2

**Comment by GoPikachue** [comment]
所以我有点疑惑这里的维度设置是为什么这样子处理的0.0

**Comment by GoPikachue** [comment]
就是对于亚像素卷积来说，给它过多的特征，也不会有太多的帮助，所以就适当减低通道数是嘛？

**Comment by GoPikachue** [comment]
噢噢，原来是这样子！
谢谢你的耐心答复！
