### ISSUE TITLE
关于Mult-Adds和Params的计算

### ISSUE THREAD

**Issue by EchoXu98** [icandle/MAN#19]
大佬，请问能否提供下您计算网络的Mult-Adds和Params的代码？我用了在网上找的代码进行测试，Params计算与论文中一样，但是Mult-Adds计算不正确。

**Comment by icandle** [comment]
Multi-Adds的话是这个，FLOPs用KAIR里面的from utils.utils_modelsummary import get_model_activation, get_model_flops，可以参考main_challenge_sr.py

from torchsummaryX import summary

net = model()  

#x4
summary(model, torch.zeros((1, 3, 320, 180)))
#x3
#summary(model, torch.zeros((1, 3, 427, 240)))
#x2
#summary(model, torch.zeros((1, 3, 640, 360)))

**Comment by EchoXu98** [comment]
好的，谢谢大佬的快速回复！我去试试看
