### ISSUE TITLE
Mult-Adds

### ISSUE THREAD

**Issue by EchoXu98** [icandle/MAN#22]
大佬，请问下你论文中测试Multi-Adds指标的代码在哪里有？没找到可不可以提供下？我用的测试x2尺寸的，设置输入的尺寸为1x3x640x320结果爆显存了。如下所示，我给出我用的测试代码。
`import time
import argparse
import torch, warnings
from archs.MAN_arch import MAN
from torchprofile import profile_macs
from thop import profile

parser = argparse.ArgumentParser()
parser.add_argument('--model', default='MAN', type=str, help='model name')
parser.add_argument('--device', default='cuda', type=str, help='test device')
parser.add_argument('--profiler', action='store_true', default=False, help='use profiler')
args = parser.parse_args()

warnings.filterwarnings('ignore')

if __name__ == '__main__':
	test_w = [256]
	test_h = [256]
	test_iter = [1]
	test_epoch = 1

	network = eval(args.model)()
	network.to(args.device)
	network.eval()

	macs = profile_macs(network, torch.rand([1, 3, 128, 128]).to(args.device))
	macs_G = macs / (1024**3)

	_, params = profile(network, inputs=(torch.rand([1, 3, 128, 128]).to(args.device), ))
	params_M = params / (1024 ** 2)

	with torch.no_grad():
		for (h, w, it) in zip(test_w, test_h, test_iter):
			rand_img = torch.rand([1, 3, h, w]).to(args.device)
			trace_network = torch.jit.trace(network, [rand_img])

			if args.profiler:							# torch.profiler slows down the model
				with torch.profiler.profile(
					activities=[
						torch.profiler.ProfilerActivity.CPU,
						torch.profiler.ProfilerActivity.CUDA,
					]
				) as p:

					for _ in range(it):
						output = trace_network(rand_img)

				print(p.key_averages().table(
					sort_by="self_cuda_time_total", row_limit=-1))

			fps_list = []
			for i in range(test_epoch):

				torch.cuda.synchronize()
				t1 = time.time()
				
				for _ in range(it):
					output = trace_network(rand_img)

				torch.cuda.synchronize()
				t2 = time.time()

				fps = it/(t2-t1)
				fps_list.append(fps)

			fps_list = sorted(fps_list)
			avg_fps = fps_list[test_epoch//2]

			print('Input Shape: {0:s}\nParams (M): {1:.3f}\nMACs (G): {2:.3f}\nRuntime (ms): {3:.2f}'
				  .format(str((1, 3, h, w)), params_M, macs_G, 1e3 / avg_fps))`

**Comment by icandle** [comment]
参见Issue https://github.com/icandle/MAN/issues/19，使用torchsummaryX库

**Comment by EchoXu98** [comment]
好的，谢谢大佬
---- Replied Message ----
| From | Yan ***@***.***> |
| Date | 07/05/2023 12:29 |
| To | icandle/MAN ***@***.***> |
| Cc | EchoXu98 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [icandle/MAN] Mult-Adds (Issue #22) |

参见Issue https://github.com/icandle/MAN/issues/19，使用torchsummaryX库
