### ISSUE TITLE
What is the main.py or test.py ? 

### ISSUE THREAD

**Issue by fehimebetul** [icandle/MAN#4]
How to run the program.

**Comment by icandle** [comment]
The train.py and test.py are uploaded. [BasicSR](https://github.com/XPixelGroup/BasicSR/blob/master/docs/INSTALL.md) is required to run the program. You can also refer to the [basicse-example](https://github.com/xinntao/BasicSR-examples/blob/master/README.md) to adjust the repo.

**Comment by icandle** [comment]
We also renewed the readme page. Thanks for your comments.
