### ISSUE TITLE
Questions about PWConv

### ISSUE THREAD

**Issue by GoPikachue** [icandle/MAN#5]
First of all thank you for your outstanding work! Here I have some questions about modules for you:
   I find that in GroupGLKA and SGAB in the code, the PWConv of the two paths are not two different convolution cores, but torch.chunk is used to cut the same convolution kernel when the number of channels is X2. Is this inconsistent with the module schematic diagram given in the paper?
![E03S96LVM LL ` NZ29_B](https://user-images.githubusercontent.com/57658728/201028937-36b8534c-1524-490a-9242-2ba4a03c7200.png)
![Y$M~%9@7YG8Y X$X@QL3{XI](https://user-images.githubusercontent.com/57658728/201028967-28cf502f-5894-4587-9a5c-819485143e9e.png)
   Looking forward to your reply!

**Comment by icandle** [comment]
These two (1: PWConv(n,2*n) then chunk; 2: two PWConv(n,n)) should be equivalent, I think.

**Comment by GoPikachue** [comment]
Ok, thanks for getting back to me on such short notice.
