### ISSUE TITLE
PSNR and SSIM Problem

### ISSUE THREAD

**Issue by AminTolou** [icandle/MAN#9]
I have a question about calculating psnr and ssim.
as you know the size of some pictures in database set 14 , B100 and Manga 109 are not a correct multiple of 2, 3, 4, and 8. For this reason, when we downscale them to make low-resolution images and then super-resolution, we face the problem of changing the dimensions of the images.
For example, suppose that the size of HR Image (100x100) and LR/3 Image (33x33) and finally SR image is (99x99) so we should calculate psnr and ssim between HR(100x100) and SR(99x99) that they have different size and we can not calculate the PSNR and SSIM between these two image.
Is it possible to guide in this field?

**Comment by icandle** [comment]
I probably understand the problem. Actually, the images are clipped to make sure that GT and SR have consistent shape. For example, the 100*100 image will be clipped to 99*99 before testing and training. Directly computing psnr or ssim between them is unusual.

**Comment by AminTolou** [comment]
> I probably understand the problem. Actually, the images are clipped to make sure that GT and SR have consistent shape. For example, the 100x100 image will be clipped to 99x99 before testing and training. Directly computing psnr or ssim between them is unusual.

thanks . but for different scales 2,3,4,8 we must change GT to GT mod 2 ,GT Mod 3, GT Mod 4 and GT Mode 8 or we change GT to GT mode 24 (  WE HAVE DIFFERENT GT FOR EACH Scale or only  have One GT mode 24 for all scale)
GT MODE 2 FOR Picture (100x 100) is Picture with Size (100x100) ( the size of picture must be divisible  by 2)
GT MODE 3 FOR Picture (100 x 100) is Picture with Size (99x99) ( the size of picture must be divisible  by 3)
GT MODE 4 FOR Picture (100 x 100) is Picture with Size (100x100) ( the size of picture must be divisible  by 4)
GT MODE 8 FOR Picture (100 x 100) is Picture with Size (96x96) ( the size of picture must be divisible  by 8)
but 
GT Mode 24 for Picture With Size (100x100) is Picture with Size (96x96)( the size of picture must be divisible  by 24 in other words 96 is divisible by 2,3,4 and 8)
I Calculated PSNR and SSIM with GT Mode 24 for all scale But the Result for all scale and all database is  approximately 0.7-1 dB Bigger than your Result.
could you help me again?

**Comment by icandle** [comment]
Generally, it is different GT for each scale.

**Comment by icandle** [comment]
But for some dataset like Set5 they share the same GT.

**Comment by AminTolou** [comment]
> Generally, it is different GT for each scale.

thanks I will check it.

**Comment by AminTolou** [comment]
I check the result but there is some problem in calculate PSNR/SSIM. I check the result for scale 2 and use your share's model "man-base  MANx2_DF2K.pth" but result for some data base is not same with paper's result.
 for LRX2 and GT first I Resize the HR Image to the nearest divisible by 2 after that resize image using Matlab code " ImLRx2 = imresize(GT, 1/2, 'bicubic');"
the result of PSNR and SSIM shows  in the picture below..
![Capture](https://user-images.githubusercontent.com/44254357/222911165-4eedea27-8ad2-4d93-8b3b-33636a7b4025.JPG)
![image](https://user-images.githubusercontent.com/44254357/222911350-3a41ae57-8be1-4aaf-b2e2-73ae2e0e8108.png)
could you help me please?
is it possible to share LR and HR Data base for all scales for  me?
i really don't know what else to do؟

**Comment by icandle** [comment]
The Testsets are available at [Baidu NetDisk](https://pan.baidu.com/s/1dxO17ac0sPSY6SVTwo2eZQ?pwd=mans). For Datasets preparation (except Set5 and Set14), you can use [this](https://github.com/zhaohengyuan1/PAN/blob/master/codes/data_scripts/generate_mod_LR_bic.py).
